name: Class Diagram

on:
  push:
    branches: [ main ]

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instala Java, Graphviz y PlantUML
      - name: Install Java, Graphviz, and PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz plantuml

      # Instala PlantUmlClassDiagramGenerator para generar el .puml desde tu backend
      - name: Install PlantUML Class Diagram Generator
        run: |
          dotnet tool install --global PlantUmlClassDiagramGenerator
          export PATH="$PATH:$HOME/.dotnet/tools"

      # Genera el archivo .puml a partir del código del backend
      - name: Generate PUML from backend
        run: |
          mkdir -p design/output
          PlantUmlClassDiagramGenerator backend/Exam.Api -o design/output/class_diagram.puml

      # Convierte el .puml en PNG
      - name: Generate PNG
        run: |
          plantuml -tpng design/output/class_diagram.puml -o design/output

      # Sube el artefacto como resultado del workflow
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: class-diagram
          path: design/output
