name: Build and Deploy App

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/Exam.Api
          file: ./backend/Exam.Api/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/examapp-backend:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Build y Deploy a Vercel
        run: |
          cd frontend
          npm install
          npm run build
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} \
            --scope ${{ secrets.VERCEL_ORG_ID }} \
            --confirm --project ${{ secrets.VERCEL_PROJECT_ID }}



