name: Infra Diagram

on:
  push:
    paths: ['infra/**', 'design/infra/**']

jobs:
  diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies (Graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install diagrams

      - name: Generate infra diagram
        run: python design/infra/diagram_gen.py

      - name: Upload diagram artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra-diagram
          path: design/infra
