name: Infraestructura 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        working-directory: infra
        run: terraform init

      - name: Plan Terraform
        working-directory: infra
        run: terraform plan || echo "Falló el plan pero seguimos"

      - name: Apply Terraform
        working-directory: infra
        run: terraform apply -auto-approve || echo "Falló el apply pero seguimos"
