name: Publish Docs

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**', 'docs/**' ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install docfx
        run: dotnet tool install -g docfx

      - name: Build docs
        run: |
          docfx docs/docfx.json -o _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
